name: Rcpp Gallery
description: Articles and code that provide examples of using the Rcpp package
repo: https://github.com/RcppCore/rcpp-gallery

url: https://gallery.rcpp.org
permalink: "articles/:title/"

exclude: 
  - COPYING
  - README.md 
  - Makefile
  - src
  - figure

highlighter: rouge

markdown: kramdown



